### ISSUE TITLE
[FEAT] - Handle Images

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/event-submission-bot#5]
### What feature would you like to see?

Events can also take images/banners. The bot currently does not have a way to support those, but we should add such support.

We may be able to do it as simply as adding an image url? However, we may end up having to use the actual Buffer of an image data.

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by naomi-lgbt** [comment]
All yours!

**Comment by naomi-lgbt** [comment]
Closing in prep for archival
